### ISSUE TITLE
Issue with argpartition

### ISSUE THREAD

**Issue by jmart-n** [ahaldane/HOM_r20#1]
Hello! I've been encountering an error with argpartition when running make_db. It goes like this:
```
$ ./HOM_r20.py make_db test 1000 targetMSA 
Starting 16 workers...
  2     17    concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "./HOM_r20.py", line 182, in makedb_job
    return npos, i, process_marg(topmode, npos, i, pos, freq, uniq)
  File "./HOM_r20.py", line 149, in process_marg
    top = np.argpartition(f, -ntop)[-ntop:]
  File "<__array_function__ internals>", line 5, in argpartition
  File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 832, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: kth(=-9) out of bounds (11)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./HOM_r20.py", line 550, in <module>
    main()
  File "./HOM_r20.py", line 546, in main
    funcs[known_args.action](remaining_args)
  File "./HOM_r20.py", line 221, in make_db
    n, i, dat = future.result()
  File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: kth(=-9) out of bounds (11)
```

I've tried this in Python 3.9 and 3.8, with numpy versions 1.21, 1.20, and 1.19, and with highmarg/seqtools compiled on osx-arm64 and linux64. Same error each time, though if I use a lower number of samples like 1-100 it generally finishes with no errors, but not consistently. 80 samples gives an error, but 81 does not.

Let me know if you need more info from me!
thanks

**Comment by zzhongzz** [comment]
> Hello! I've been encountering an error with argpartition when running make_db. It goes like this:
> 
> ```
> $ ./HOM_r20.py make_db test 1000 targetMSA 
> Starting 16 workers...
>   2     17    concurrent.futures.process._RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
>     r = call_item.fn(*call_item.args, **call_item.kwargs)
>   File "./HOM_r20.py", line 182, in makedb_job
>     return npos, i, process_marg(topmode, npos, i, pos, freq, uniq)
>   File "./HOM_r20.py", line 149, in process_marg
>     top = np.argpartition(f, -ntop)[-ntop:]
>   File "<__array_function__ internals>", line 5, in argpartition
>   File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 832, in argpartition
>     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
>   File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
>     return bound(*args, **kwds)
> ValueError: kth(=-9) out of bounds (11)
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./HOM_r20.py", line 550, in <module>
>     main()
>   File "./HOM_r20.py", line 546, in main
>     funcs[known_args.action](remaining_args)
>   File "./HOM_r20.py", line 221, in make_db
>     n, i, dat = future.result()
>   File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/concurrent/futures/_base.py", line 437, in result
>     return self.__get_result()
>   File "/home/jmart/miniconda3/envs/hom-test/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
> ValueError: kth(=-9) out of bounds (11)
> ```
> 
> I've tried this in Python 3.9 and 3.8, with numpy versions 1.21, 1.20, and 1.19, and with highmarg/seqtools compiled on osx-arm64 and linux64. Same error each time, though if I use a lower number of samples like 1-100 it generally finishes with no errors, but not consistently. 80 samples gives an error, but 81 does not.
> 
> Let me know if you need more info from me! thanks

Same issue here. It seems like np.argpartition fails if the array is shorter than k.
I try to solve this by adding `top = np.arange(f.shape[0])` if f is too short, like this:
```ntop = int(topmode)
if f.shape[0] < ntop:
    top = np.arange(f.shape[0])
else:
    top = np.argpartition(f, -ntop)[-ntop:]
top = top[np.argsort(f[top])]```
which mean if the array f is too short, top will be all indexes in f.

**Comment by Shunsuke-1994** [comment]
I also met the same problem and managed to solve it by editing [this line](https://github.com/ahaldane/HOM_r20/blob/f2a6041a4a09c1647fc1c0831ded89802867f477/HOM_r20.py#L149) as  @zzhongzz says. Thank you very much!
